In [1]:
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

C:\Users\andrea.cortesi\AppData\Local\Programs\Python\Python36\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
def plotVectors(vecs, cols, alpha=1):
    """
    Plot set of vectors.

    Parameters
    ----------
    vecs : array-like
        Coordinates of the vectors to plot. Each vectors is in an array. For
        instance: [[1, 3], [2, 2]] can be used to plot 2 vectors.
    cols : array-like
        Colors of the vectors. For instance: ['red', 'blue'] will display the
        first vector in red and the second in blue.
    alpha : float
        Opacity of vectors

    Returns:

    fig : instance of matplotlib.figure.Figure
        The figure of the vectors
    """
    plt.figure()
    plt.axvline(x=0, color='#A9A9A9', zorder=0)
    plt.axhline(y=0, color='#A9A9A9', zorder=0)

    for i in range(len(vecs)):
        x = np.concatenate([[0,0],vecs[i]])
        plt.quiver([x[0]],
                   [x[1]],
                   [x[2]],
                   [x[3]],
                   angles='xy', scale_units='xy', scale=1, color=cols[i],
                   alpha=alpha)

In [3]:
# make two random 3x3 matrices

A = np.random.randint(0, high=10, size=(3,3))
B = np.random.randint(0, high=10, size=(3,3))

In [4]:
A

array([[3, 5, 5],
       [1, 8, 9],
       [9, 0, 6]])

In [5]:
B

array([[2, 1, 7],
       [7, 0, 0],
       [7, 0, 0]])

In [6]:
# multiplication entre les deux matrices

np.matmul(A,B)

array([[ 76,   3,  21],
       [121,   1,   7],
       [ 60,   9,  63]])

In [7]:
# la multiplication entre matrices n'est pas commutative

np.matmul(B,A)

array([[70, 18, 61],
       [21, 35, 35],
       [21, 35, 35]])

In [13]:
# random 3x1 vector
v = np.random.randint(-10, high=10, size=(3,1))

In [14]:
v

array([[ 6],
       [-3],
       [-7]])

In [15]:
multiplication matrice vecteurs

np.matmul(A,v)

array([[ 18],
       [-16],
       [-42]])

In [ ]:
# exemple changement de base

In [37]:
# matrice initiale diagonale

C=np.array([[-1,0],[0,2]])
C

array([[-1,  0],
       [ 0,  2]])

In [38]:
P=np.array([[1,1],[-1,1]])
P

array([[ 1,  1],
       [-1,  1]])

In [39]:
CC = np.matmul(P,np.matmul(C,np.linalg.inv(P)))
CC

array([[0.5, 1.5],
       [1.5, 0.5]])

In [40]:
np.matmul(np.linalg.inv(P),np.matmul(CC,P))

array([[-1.,  0.],
       [ 0.,  2.]])

In [41]:
w=np.array([[1],[3]])
w

array([[1],
       [3]])

In [42]:
np.matmul(CC,w)

array([[5.],
       [3.]])