# Part 1 : livecoding

### - Charger numpy

In [2]:
import numpy as np

### 1) Toutes les méthodes d'initialisation
- initialiser un tableau rempli de zeros de 10 éléments

In [ ]:
np.zeros(10)


- Initialiser une matrice remplie de zeros !!! d'entiers !!! de dimensions 5,10

In [6]:
np.zeros((5, 10), dtype=int)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

- créer un tableau à partir d'une liste de 100 éléments contenant tout les entiers entre 1 et 100. On pourrait le faire directement avec numpy également.

In [5]:
np.array(range(100))



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

- initialiser une matrice de taille (2,2,3) de valeur constante 42

In [10]:
np.full((2, 2, 3), 42)


array([[[42, 42, 42],
        [42, 42, 42]],

       [[42, 42, 42],
        [42, 42, 42]]])

- initialiser une matrice non initialsée de taille 3,3.
empty() est plus rapide que zeros(), mais sans garantie sur les valeurs contenues

In [11]:
np.empty((3, 3))


array([[2.72141792e-316, 2.31297541e-312, 2.44029516e-312],
       [2.22809558e-312, 2.33419537e-312, 2.12199579e-312],
       [2.33419537e-312, 2.14321575e-312, 4.94065646e-322]])

- initialiser une matrice identité de taille 4

In [12]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- créer un tableau avec 7 valeurs réparties équitablement entre 1 et 3.5. Méthode très utilisée pour les graphes, pour échantilloner à intervalle régulier et afficher ces points

In [18]:
np.linspace(1, 3.5, 7)


array([1.        , 1.41666667, 1.83333333, 2.25      , 2.66666667,
       3.08333333, 3.5       ])

- créer un tableau de taille (2,2,3) de chaine de 4 caractère contenant "ynov" dans chaque case. La taille de chaque chaine doit forcément être la même.

In [20]:
np.full((2, 2, 3), fill_value="ynov")


array([[['ynov', 'ynov', 'ynov'],
        ['ynov', 'ynov', 'ynov']],

       [['ynov', 'ynov', 'ynov'],
        ['ynov', 'ynov', 'ynov']]], dtype='<U4')

conversion entre pandas dataframe et numpy array

In [21]:
import pandas as pd
df = pd.DataFrame([[1,2],[3,4]])
df

0  1
0  1  2
1  3  4

In [23]:
arr = np.array(df)

la premiere dimension encode les lignes :

In [24]:
arr[0]

array([1, 2])

## 2) Charger et sauvegarder ses valeurs

In [25]:
my_array = np.full((1000,1000),42)
my_array

array([[42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       ...,
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42]])

- sauvegarder ce tableau

In [26]:
np.save("../data/array", my_array)

- charger le tableau sauvegardé et vérifier qu'il est bien égal au précédent

In [27]:
np.load("../data/array.npy") == my_array

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

- on peut aussi sauvegarder en format compressé. Volume moins important, mais plus long à lire comme necessite decompression. Utilisé pour archiver mais pas pour stocker des données que l'on va utiliser par la suite.

In [29]:
np.savez_compressed("../data/array", my_array)

AttributeError: module 'numpy' has no attribute 'save_compressed'

- on peut sauvegarder et charger plusieurs tableaux dans le même fichier. Utile pour sauvegarder les données et les labels, et garantir qu'on utilise bien les labels correspondants aux données !

In [32]:
arr = np.zeros(3)


In [33]:
np.savez("../data/myarrays", array1=arr, array2=arr)

In [34]:
np.load("../data/myarrays.npz")["array1"]


array([0., 0., 0.])

## 3) Obtenir de l'information sur le contenu d'un tableau

- La taille

In [35]:
arr.size

3

- le nombre d'element

In [ ]:
arr.size

- le type

In [ ]:
arr.dtype

On peut changer ce type, pour pouvoir encoder plus de valeurs, faire passer des flottants en entiers ou encore réduire la taille en mémoire d'un tableau.

In [37]:
arr.astype(np.int16)


array([0, 0, 0], dtype=int16)

## 4) Les opérations matricielles

In [38]:
a = np.array([[12,3,4],[0,0,-2]])
b = np.array([[11,2,3],[4,0,2]])
c = np.array([1,2,3])
d = np.array([2,3])

- addition, soustraction

In [39]:
a - b

array([[ 1,  1,  1],
       [-4,  0, -4]])

In [42]:
a + c

array([[13,  5,  7],
       [ 1,  2,  1]])

Attention au résultat si les tableaux n'ont pas la même dimension, cela ne va pas toujours lever des erreurs

- multiplication et division

In [47]:
a * b


array([[132,   6,  12],
       [  0,   0,  -4]])

- la transposée

In [48]:
a.transpose()


array([[12,  0],
       [ 3,  0],
       [ 4, -2]])

- le produit matriciel

In [50]:
a.dot(c)


array([30, -6])

Dot d'un vecteur par lui même nous donne sa norme (longueur) au carré

In [51]:
a.dot(a)


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

On peut calculer l'angle entre deux vecteurs avec dot (et arcos)

In [53]:
import math
v1 = np.array((0,1))
v2 = np.array((1,0))
angle = math.acos(
  v1.dot(v2) / (np.sqrt(v1.dot(v1))+ np.sqrt(v2.dot(v2)))
)# angle en radian
print("Angle entre v1 et v2 : ",angle/np.pi*180, "degré") # converti en degré

Angle entre v1 et v2 :  90.0 degré


## 5) Comparaison et aggrégations de tableau

- Les comparaisons

In [54]:
a == b

array([[False, False, False],
       [False,  True, False]])

In [55]:
a < b

array([[False, False, False],
       [ True, False,  True]])

In [56]:
a > b

array([[ True,  True,  True],
       [False, False, False]])

In [57]:
a != b

array([[ True,  True,  True],
       [ True, False,  True]])

Applications : remplacer par 0 les cases ou a est strictement superieur à b

In [65]:
a

array([[12,  3,  4],
       [ 0,  0, -2]])

In [66]:
b

array([[11,  2,  3],
       [ 4,  0,  2]])

In [68]:
e = a.copy()
e[a == b] = 42
e

array([[12,  3,  4],
       [ 0, 42, -2]])

Et l'égalité de tableau ?

In [75]:
np.array_equal(a, a.copy())


True

- Trier un tableau:

In [86]:
e = a.copy()
print(e)
e.sort(axis=1)
e

[[12  3  4]
 [ 0  0 -2]]


array([[ 3,  4, 12],
       [-2,  0,  0]])

- les aggrégations : sum, mean, median, min, max, std,...

In [76]:
a.sum()

17

In [77]:
a.mean()


2.8333333333333335

In [79]:
np.median(a)

1.5

In [80]:
a.min()

-2

In [81]:
a.max()

12

In [82]:
a.std()

4.561310727801336

- on peut préciser sur quels axes les appliquer

In [83]:
a.mean(axis=1)

array([ 6.33333333, -0.66666667])

## 6) accéder aux éléments

In [85]:
a[0,0]


12

- Slicing. C'est un moyen efficace pour manipuler, acceder et copier plusieurs elements comme il ne demande pas un acces aux elements un par un.

## 7) Autres fonctions pratiques en datascience

- beaucoup de fonctions et utilitaires mathématiques sont présents dans numpy

In [88]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [89]:
a.reshape((8, 2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

- changer la taille du tableau

- nan et inf values

In [91]:
np.isnan(a)
a == np.nan


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

- Detecter et remplacer les nan

In [ ]:
np.nan_to_num(a, nan=7)

- le cas des inf


In [94]:
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [93]:
a[~np.isinf(a)] = 0


- remplacer infs et nan par une valeur:

- remplacer les inf par la valeur maximum non inf :